version: '3'

services:
# Windows with Docker Desktop WSL 2 backend
# The vm.max_map_count setting must be set in the docker-desktop container:
# wsl -d docker-desktop
# sysctl -w vm.max_map_count=262144
# https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    env_file:
      - elasticsearch.env
    ports:
      - "9200:9200"
    container_name: elasticsearch
    networks:
      - bus-dev-utils

  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.1
    ports:
      - "5601:5601"
    container_name: kibana
    networks:
      - bus-dev-utils

  mysql:
    image: mysql:8
    restart: always
    container_name: mysql
    environment:
      MYSQL_USER: dbUser
      MYSQL_PASSWORD: dbPassword
      MYSQL_ROOT_PASSWORD: dbPassword
      MYSQL_DATABASE: dbDatabase
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - bus-dev-utils

  nats:
    image: nats:2.1
    container_name: nats
    ports:
      - "4222:4222"
    networks:
      - bus-dev-utils

  redis:
    image: redis:6.0
    command: redis-server /usr/local/etc/redis/redis.conf
    container_name: redis
    volumes:
      - ./redis/:/usr/local/etc/redis/
    ports:
      - "6379:6379"
    networks:
      - bus-dev-utils

networks:
  bus-dev-utils:
    name: bus-dev-utils
